# -*- coding: utf-8 -*-
"""MSobol_ModelTrending_Midterm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17t60EQvDL6sUCmi3BkNfwZ-ufKoaI3Yl

##Import Libraries
"""

# Load processing and plotting libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from git import Repo
import os

# Load stats libraries
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, root_mean_squared_error

import warnings
warnings.filterwarnings("ignore")

"""##Import Repo and Read Data"""

# Clone the motorcycle scraper repo to a local folder

repo_url = "https://github.com/OPIM5512-mii24004/myscraper-mii24004-v3"
local_dir = "/Users/madisonsobol/Desktop/OPIM5512/Midterm" # Edit to your desired folder
cloned_repo = Repo.clone_from(repo_url, local_dir)

# Define repo path and pull results from github as data is syncing

repo_path = "/Users/madisonsobol/Desktop/OPIM5512/Midterm"
repo = Repo(repo_path)
repo.remotes.origin.pull()

# Compile pred CSV files

pred_results = os.path.join(repo_path,"results")
pred_dfs = []

for file in os.listdir(pred_results):
    if file.endswith('.csv'):
     pred_files = os.path.join(pred_results,file)
     df = pd.read_csv(pred_files)

     run_id = file.split("-")[0]
     df["run_id"] = run_id

     pred_dfs.append(df)

pred_df = pd.concat(pred_dfs, ignore_index=True)

pred_df.shape

# Clean pred results df

pred_df['scraped_at'] = pd.to_datetime(pred_df['scraped_at'])
pred_df = pred_df.dropna(subset=["actual_price","pred_price"])

pred_df.shape

# Compile permutation importance CSV files

perm_results = os.path.join(repo_path,"perm_results")
perm_dfs = []

for file in os.listdir(perm_results):
    if file.endswith('.csv'):
     perm_files = os.path.join(perm_results,file)
     df = pd.read_csv(perm_files)

     run_id = file.split("-")[0]
     df["run_id"] = run_id

     perm_dfs.append(df)

perm_df = pd.concat(perm_dfs, ignore_index=True)

perm_df.shape

"""## Compute Performance Metrics by Run ID"""

# Compute metrics grouped by run id

pred_df['residual'] = pred_df['actual_price'] - pred_df['pred_price']

metrics = pred_df.groupby('run_id').apply(
    lambda x: pd.Series({
        'mae': mean_absolute_error(x['actual_price'], x['pred_price']),
        'mape': mean_absolute_percentage_error(x['actual_price'], x['pred_price']),
        'rmse': root_mean_squared_error(x['actual_price'], x['pred_price'])
    })
).reset_index()

metrics

"""## Visualizing Model Results"""

# Plot Actual vs Predicted

plt.figure(tight_layout=True)
plt.scatter(pred_df.actual_price,pred_df.pred_price)
plt.plot([pred_df['actual_price'].min(), pred_df['actual_price'].max()],
         [pred_df['actual_price'].min(), pred_df['actual_price'].max()],
         color='red', linestyle='--', linewidth=1.5, label="slope = 1")

plt.xlabel('Actual Price',fontweight='bold')
plt.ylabel('Predicted Price',fontweight='bold')
plt.title('Actual vs Predicted Price',fontweight='bold')
plt.legend()
plt.show()

print('PERFORMANCE METRICS:',
      '\nMAE:', "\n", metrics.mae.values,
      '\nMAPE:', "\n", metrics.mape.values,
      '\nRMSE:', "\n", metrics.rmse.values)

#Track residual change over time

plt.figure(figsize=(8,6),tight_layout=True)
plt.scatter(pred_df.scraped_at,pred_df.residual)
plt.xticks(rotation=45)

plt.xlabel('Time Scraped',fontweight='bold',fontsize=12)
plt.ylabel('Residual',fontweight='bold',fontsize=12)
plt.title('Residual Change Over Time',fontweight='bold',fontsize=14)
plt.show()

#Track mae change over time

plt.figure(tight_layout=True)
plt.plot(metrics.run_id,metrics.mae)
plt.xticks(rotation=45)

plt.xlabel('Run ID',fontweight='bold')
plt.ylabel('MAE',fontweight='bold')
plt.title('MAE Change Over Time',fontweight='bold')
plt.show()

#Track mape change over time

plt.figure(tight_layout=True)
plt.plot(metrics.run_id,metrics.mape)
plt.xticks(rotation=45)

plt.xlabel('Run ID',fontweight='bold')
plt.ylabel('MAPE',fontweight='bold')
plt.title('MAPE Change Over Time',fontweight='bold')
plt.show()

#Track rmse change over time

plt.figure(tight_layout=True)
plt.plot(metrics.run_id,metrics.rmse)
plt.xticks(rotation=45)

plt.xlabel('Run ID',fontweight='bold')
plt.ylabel('MAPE',fontweight='bold')
plt.title('RMSE Change Over Time',fontweight='bold')
plt.show()

# Track feature importance over time

plt.figure(figsize=(10,6),tight_layout=True)
sns.lineplot(data=perm_df, x='run_id', y='Importance', hue='Features', marker='o')
plt.xticks(rotation=45)

plt.xlabel('Run ID', fontweight="bold")
plt.ylabel('Permutation Importance',fontweight="bold")
plt.title('Feature Importance Over Time',fontweight="bold")
plt.legend(bbox_to_anchor=(1.05, 1.02), loc='upper left')
plt.show()

"""## Final Comments at the Time of Submission
1. The decision tree model seems to perform okay at predicting motorcycle prices based on the actual vs predicted plot.
2. Based on the evaluation metrics and feature importance plot, I would be interested in adjusting the fields of interest to increase model performance.
3. The MAE, MAPE, and RMSE plots over time demonstrate a successful pipeline where model predications are synced to GitHub, cloned, and incorporated into a flexible framework for visualization.
4. The results of permutation importance show that mileage and engine displacement i.e., CC are the primary features dictating the model's predictive capability.
"""

